// Generate src/geo/data/regionalColumns.ts from the regional-geology research
// workflow output. Usage: node scripts/buildRegional.mjs <output.json>
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const src = process.argv[2];
const d = JSON.parse(readFileSync(src, 'utf8'));
const regions = (d.result?.regions ?? []).filter(Boolean);

function hexNum(h) {
  const m = String(h).match(/[0-9a-fA-F]{6}/);
  return m ? parseInt(m[0], 16) : 0x999999;
}
function shortName(province, city) {
  const cut = province.split(/[(—,]/)[0].trim();
  return (cut || city).slice(0, 48);
}
function sanitizeLayers(layers) {
  const out = [];
  let prev = 0;
  for (const l of layers) {
    const topM = Math.max(0, Number(l.topM) || prev);
    let botM = Number(l.botM);
    if (!(botM > topM)) botM = topM + 1;
    out.push({ name: String(l.name).replace(/\s+/g, ' ').trim(), topM, botM, hex: hexNum(l.hex) });
    prev = botM;
  }
  return out;
}
function area(b) { return Math.max(0.01, (b.north - b.south) * (b.east - b.west)); }

const cols = regions
  .filter((r) => r.bbox && Array.isArray(r.layers) && r.layers.length)
  .map((r) => ({
    name: shortName(r.province, r.city),
    bbox: [r.bbox.south, r.bbox.north, r.bbox.west, r.bbox.east],
    layers: sanitizeLayers(r.layers),
    _area: area(r.bbox),
  }))
  .sort((a, b) => a._area - b._area); // smallest (most specific) first → lookup picks it

const esc = (s) => `'${s.replace(/\\/g, '\\\\').replace(/'/g, "\\'")}'`;
const lines = cols.map((c) => {
  const ls = c.layers
    .map((l) => `    { name: ${esc(l.name)}, topM: ${l.topM}, botM: ${l.botM}, hex: 0x${l.hex.toString(16).padStart(6, '0')} },`)
    .join('\n');
  return `  { name: ${esc(c.name)}, bbox: [${c.bbox.join(', ')}], layers: [\n${ls}\n  ] },`;
}).join('\n');

const out = `// AUTO-GENERATED by scripts/buildRegional.mjs — do not edit by hand.
// Published regional stratigraphy for major population centres, used as an
// override to the coarse global CRUST1.0 model. Layer names are scientific
// English (international nomenclature); depths are metres below the surface.
// Sorted smallest-bbox first so a point-in-box lookup picks the most specific.

export interface RegionalColumn {
  name: string; // geological province
  bbox: [number, number, number, number]; // [south, north, west, east]
  layers: Array<{ name: string; topM: number; botM: number; hex: number }>;
}

export const REGIONAL_COLUMNS: RegionalColumn[] = [
${lines}
];
`;

const dest = join(ROOT, 'src', 'geo', 'data', 'regionalColumns.ts');
writeFileSync(dest, out);
console.log(`Wrote ${dest}: ${cols.length} regions, ${cols.reduce((s, c) => s + c.layers.length, 0)} layers`);
